#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/rms ~/bookmarks/i/it/courses ~/bookmarks/i/it/projects -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi


selected_name=$(basename "$selected" | tr . _)
# Special handling for rms directory
if [[ $selected == */rms/* ]]; then
    selected_name="work_$(basename "$selected" | tr . _)"
else
    selected_name=$(basename "$selected" | tr . _)
fi
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi
