--source $HOME/.config/nvim/themes/gruvbox-light.vim
--source $HOME/.config/nvim/themes/solarized.vim
--source $HOME/.config/nvim/plug-config/plugins.vim
--source $HOME/.config/nvim/themes/gruvbox-dark.vim
--source $HOME/.config/nvim/themes/start-screen.vim
--source $HOME/.config/nvim/themes/airline.vim
require "user.lsp-config"
require "user.treesiter"
require "user.sas-telescope"
require "user.mappings"
require "user.settings"
require "user.plugins"
require "user.colorscheme"
require "user.bufferline"
require "user.lualine"
require "user.impatient"
require "user.indentline"
require "user.cmp"
require "user.alpha"
require "user.project"
